Repository BotsBurgh/BOTSBURGH-FTC-2024-25, pull requests merged in 2024-07, with the labels that each got.

#36 `TriWheels` localization
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TriWheels.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleop/demos/EncoderLocalizationDemo.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/Math.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/Polar2d.kt
  TeamCode/src/test/kotlin/org/firstinspires/ftc/teamcode/api/TriWheelsTest.kt
  TeamCode/src/test/kotlin/org/firstinspires/ftc/teamcode/utils/MathTest.kt
Labels: A-Autonomous, C-Feature, S-Needs-Review

#39 Common tasks
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/demos/DemoAPI.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/demos/DemoLinearAPI.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/autonomous/demos/DemoAuto.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleop/demos/DemoTeleOp.kt
Labels: A-Cross-Cutting, S-Needs-Review

#42 TeleOpMain Wheel Movement
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotConfig.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleop/TeleOpMain.kt
Labels: A-Teleop, C-Feature

#44 `Polar2dDual` and `DualNum.atan()`
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/Math.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/Polar2d.kt
  TeamCode/src/test/kotlin/org/firstinspires/ftc/teamcode/utils/MathTest.kt
Labels: A-Autonomous, C-Feature, S-Needs-Review
