Repository BotsBurgh/BOTSBURGH-FTC-2024-25, pull requests merged in 2024-08, with the labels that each got.

#46 Update to Road Runner 1.0
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/Math.kt
  gradle/libs.versions.toml
Labels: A-Autonomous, C-Dependencies, S-Needs-Review

#47 Kiwi Kinematics
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/TriWheels.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/roadrunner/KiwiKinematics.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/utils/Polar2d.kt
Labels: A-Autonomous, C-Feature, S-Needs-Review

#48 Logging
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotConfig.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/Logging.kt
Labels: A-Diagnostics, C-Feature, S-Waiting-On-Author

#49 Create `KiwiLocalizer`
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotConfig.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/roadrunner/KiwiLocalizer.kt
Labels: A-Autonomous, C-Feature, S-Needs-Review

#60 Just a few small fixes :)
  FtcRobotController/build.gradle
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotConfig.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/CsvLogging.kt
  TeamCode/src/test/kotlin/org/firstinspires/ftc/teamcode/utils/IsNullTest.kt
  build.common.gradle
Labels: A-Cross-Cutting, C-Code-Quality, S-Needs-Review

#62 Kiwi drive
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotConfig.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/roadrunner/FollowTrajectoryAction.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/roadrunner/KiwiDrive.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/roadrunner/KiwiLocalizer.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/roadrunner/TurnAction.kt
Labels: A-Autonomous, C-Feature, S-Needs-Testing, S-Needs-Review

#59 Fix `RobotConfig`'s package
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotConfig.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/CsvLogging.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/roadrunner/KiwiDrive.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/api/roadrunner/KiwiLocalizer.kt
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/teleop/TeleOpMain.kt
Labels: A-Cross-Cutting, C-Bug, S-Needs-Review
